### PR TITLE
Adding additional info about a lib usage

### PR DESCRIPTION
**Pull request by AndrewBogdanovTSS**
fixes https://github.com/Developmint/nuxt-svg-loader/issues/7

### CODE REVIEW

**Comment by manniL** [comment]
@AndrewBogdanovTSS Thanks a lot!

One small question: Why would you add it as `devDependency` and not as `dependency`?

I'll usually add everything as `dependency` that's needed to rebuild my stuff on my server. (If you are just want to start it there, I see the point only adding `nuxt-start` and other critical deps there)

**Comment by AndrewBogdanovTSS** [comment]
@manniL I was just following the recommendation of (vue-svg-loader)[https://github.com/visualfanatic/vue-svg-loader]. They add it as a dev dependency.

**Comment by manniL** [comment]
This makes total sense for a Vue application. I'd go with adding it to the `dependencies` though to stay in line with the other Nuxt modules (eg. axios, auth-module, ...)

**Comment by manniL** [comment]
Thank you for your contribution ☺️

**Pull request merged**
