### PR TITLE
Import svg as file instead of esModule

### PR DESCRIPTION
**Pull request by mrleblanc101**

### CODE REVIEW

**Comment by mrleblanc101** [comment]
@manniL Could you please look into this when you have some time ?

**Comment by mkegoldberg** [comment]
This would be a helpful fix for our application too! I hope this can be merged in at some point

**Comment by mrleblanc101** [comment]
@mkegoldberg I think this is abandoned. I've moved to  [@nuxtjs/svg](https://github.com/nuxt-community/svg-module) since they merged a feature I needed; Custom SVGO options to remove fill and stroke which is the reason I was using this package instead.

**Comment by mkegoldberg** [comment]
Thanks @mrleblanc101, I believe you're right. No activity for a couple years now.

**Comment by EthanDunfordAspect** [comment]
Hey, any updates for this pr?

**Pull request merged**
