### PR TITLE
feat: proper loading svg used as background url

### PR DESCRIPTION
**Pull request by 3b3ziz**
Resolves https://github.com/Developmint/nuxt-svg-loader/issues/30

Using same approach in https://github.com/egoist/svg-to-vue-component/issues/18#issuecomment-457165759 by using file-loader when the issuer is a CSS/LESS/SASS/SCSS file. Otherwise, webpack will use svg-to-vue-component loader as usual.

### CODE REVIEW

**Comment by 3b3ziz** [comment]
@manniL Would you please check this pull request and tell if anything else should be changed?

**Comment by manniL** [comment]
Will do the next days! Sorry for the delay @3b3ziz

**Comment by 3b3ziz** [comment]
@manniL Good approach but I removed also the issuer so we can use `<style>` inside .vue files.

**Comment by manniL** [comment]
Perfect :+1: 	

Now two more things:
1. Change the PR title from fix to feat (as it is a feature now)
2. Please add it to the README :relaxed:

**Comment by 3b3ziz** [comment]
@manniL done.

**Comment by 3b3ziz** [comment]
@manniL Hello, does my pull request still need some changes?

**Comment by manniL** [comment]
Hey :wave: 	I don't think so, but haven't had the time yet again to check

**Pull request merged**
